// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvtlrqrpdldlianoudys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2dGxycXJwZGxkbGlhbm91ZHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Njk3MTIsImV4cCI6MjA2OTM0NTcxMn0.6BZb-k1CSfo47k6z-HahwXcJEg_Lnvfywk3XyvU9UaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});